export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";


export const SHOW_ALERT_TRUE = "SHOW_ALERT_TRUE";
export const SHOW_ALERT_FALSE = "SHOW_ALERT_FALSE";